### ISSUE TITLE
parallel_apply

### ISSUE THREAD

**Issue by borisRa** [nalepae/pandarallel#108]
Hi,

I have relatively big pandas df , trying to run 'parallel_apply' sometimes it take huge timse to start and sometimes it is just stuck.

Example  :

pandarallel.initialize(nb_workers= min(int( os.cpu_count() - 1 ),40), use_memory_fs = False )
my_df.parallel_apply( my_fun, arg1,arg2,....,argn)

Any tips ?

Thanks,
Boris

**Comment by borisRa** [comment]
Any response ?

**Comment by allenzdd** [comment]
same problem

**Comment by till-m** [comment]
Hi @borisRa, sorry for the delay. I assume this is solved/no longer relevant. If that is not the case, feel free to reopen with a complete minimal working example.
