### ISSUE TITLE
nb_workers should be overrideable at each individual progress call

### ISSUE THREAD

**Issue by BrannonKing** [nalepae/pandarallel#124]
Presently `nb_workers` has to be set in the initialize call. If you pass it to `parallel_map` it gives an error about the value being set twice. I would like the ability to use `parallel_*` calls in some places where my code is not thread-safe -- I like the pretty progress bar but need to pass `nb_workers=1` in those places.

**Comment by pratik-choudhari** [comment]
@BrannonKing You can use plain pandas apply instead of parallel_apply in such cases
