### ISSUE TITLE
I installed pandarallel on win 64-bit, but it can't work

### ISSUE THREAD

**Issue by jiahe224** [nalepae/pandarallel#125]
On this page, https://anaconda.org/Bjrn/pandarallel, I successfully imported pandarallel on win 64bit, but it prompts  "  'DataFrame' object has no attribute 'parallel_applymap'  "  when using it. so, Why can I install it but not use it successfully?

**Comment by MohitJuneja** [comment]
@jiahe224 How did you try to import and use the library? 
Did you do something like below? If no, could you try this pattern first? Also, ensure that you are able to import pandarallel without errors.

from pandarallel import pandarallel
pandarallel.initialize()

df = pd.DataFrame(...)
df.parallel_apply(lambda x: some_func(x))

**Comment by jiahe224** [comment]
@MohitJuneja yes. There is no error when I import pandarallel, I try to rerun the following code
`from pandarallel import pandarallel
pandarallel.initialize()
test = pd.DataFrame({'a':[1,2,3]})
test = test.parallel_applymap(lambda x:x+x)`

But this time the error message is not " 'DataFrame' object has no attribute 'parallel_applymap' ", it as follows:

AttributeError                            Traceback (most recent call last)
<ipython-input-8-819600ba05bf> in <module>
      1 test = pd.DataFrame({'a':[1,2,3]})
----> 2 test = test.parallel_apply(lambda x:x+x)

C:\ProgramData\Anaconda3\lib\site-packages\pandarallel\pandarallel.py in closure(data, func, *args, **kwargs)
    439 
    440         try:
--> 441             pool = Pool(
    442                 nb_workers, worker_init, (prepare_worker(use_memory_fs)(worker),),
    443             )

C:\ProgramData\Anaconda3\lib\multiprocessing\context.py in Pool(self, processes, initializer, initargs, maxtasksperchild)
    117         '''Returns a process pool object'''
    118         from .pool import Pool
--> 119         return Pool(processes, initializer, initargs, maxtasksperchild,
    120                     context=self.get_context())
    121 

C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py in __init__(self, processes, initializer, initargs, maxtasksperchild, context)
    210         self._processes = processes
    211         try:
--> 212             self._repopulate_pool()
    213         except Exception:
    214             for p in self._pool:

C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py in _repopulate_pool(self)
    301 
    302     def _repopulate_pool(self):
--> 303         return self._repopulate_pool_static(self._ctx, self.Process,
    304                                             self._processes,
    305                                             self._pool, self._inqueue,

C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py in _repopulate_pool_static(ctx, Process, processes, pool, inqueue, outqueue, initializer, initargs, maxtasksperchild, wrap_exception)
    324             w.name = w.name.replace('Process', 'PoolWorker')
    325             w.daemon = True
--> 326             w.start()
    327             pool.append(w)
    328             util.debug('added worker')

C:\ProgramData\Anaconda3\lib\multiprocessing\process.py in start(self)
    119                'daemonic processes are not allowed to have children'
    120         _cleanup()
--> 121         self._popen = self._Popen(self)
    122         self._sentinel = self._popen.sentinel
    123         # Avoid a refcycle if the target function holds an indirect

C:\ProgramData\Anaconda3\lib\multiprocessing\context.py in _Popen(process_obj)
    325         def _Popen(process_obj):
    326             from .popen_spawn_win32 import Popen
--> 327             return Popen(process_obj)
    328 
    329     class SpawnContext(BaseContext):

C:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     91             try:
     92                 reduction.dump(prep_data, to_child)
---> 93                 reduction.dump(process_obj, to_child)
     94             finally:
     95                 set_spawning_popen(None)

C:\ProgramData\Anaconda3\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

AttributeError: Can't pickle local object 'prepare_worker.<locals>.closure.<locals>.wrapper'

**Comment by nalepae** [comment]
I see you are running on Windows.

The `README.md` says:

> Requirements
On Windows, Pandaral·lel will works only if the Python session (python, ipython, jupyter notebook, jupyter lab, ...) is executed from Windows Subsystem for Linux (WSL).
> On Linux & macOS, nothing special has to be done.

Did you do the WSL step ?

**Comment by jiahe224** [comment]
I didn't run it on WSL because it wasn't required on the page (https://anaconda.org/bjrn/pandarallel), although I knew before that that pandarallel required WSL, but then I thought that since it could be installed and imported properly, it should be able to run on win

**Comment by nalepae** [comment]
Actually I'm not the owner of https://anaconda.org/bjrn/pandarallel.

(The version seems out of date).

The official way to install `pandarallel` is to use `pip` or to use this github repository.
