### ISSUE TITLE
OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by borisRa** [nalepae/pandarallel#127]
Hi,

Hi, How can I prevent the space error bellow ?

```
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/anaconda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/anaconda/lib/python3.6/site-packages/pandarallel/pandarallel.py", line 64, in global_worker
    return _func(x)
  File "/anaconda/lib/python3.6/site-packages/pandarallel/pandarallel.py", line 120, in wrapper
    pickle.dump(result, file)
OSError: [Errno 28] No space left on device
```

Thanks !
Boris

**Comment by nalepae** [comment]
Hi,

I guess this issue is unrelated to `pandarallel`.
It seems your hard drive is simply full.
So you may remove some files from you drive...

**Comment by borisRa** [comment]
It happens only when I am using `pandarallel` on relatively big data frame .
This config does work  : ` pandarallel.initialize(use_memory_fs = False )`
Found some  related answer [here  ](https://stackoverflow.com/questions/43573500/no-space-left-while-using-multiprocessing-array-in-shared-memory)  and [here ](https://www.kaggle.com/getting-started/45288)

How can I set the temp folder to : `/tmp` when using  `pandarallel` ?

**Comment by abhineetgupta** [comment]
Same issue with a large dataframe, likely seems to be occurring because `/dev/shm` is full.

**Comment by pankaj-kvhld** [comment]
If working with Docker, the default for /dev/shm is only 64M.

**Comment by pbidro** [comment]
I got the same issue running a scrapper with pandarallel in 30 threads. 
Now im testing with this tricks:
`python 
import os
os.environ['JOBLIB_TEMP_FOLDER'] = '/tmp'
pandarallel.initialize(nb_workers=threads,progress_bar=True,verbose=2,use_memory_fs = False )
`
give me luck !

**Comment by borisRa** [comment]
T

> This is the solution:
> 
> `import os`
> 
> `os.environ['JOBLIB_TEMP_FOLDER'] = '/tmp' ` `pandarallel.initialize(nb_workers=30,progress_bar=True,verbose=2,use_memory_fs = False ) `

Thank you very much !

**Comment by borisRa** [comment]
> In my case I also had to clean up the /tmp folder.

Thanks ! combined the both solutions .

Like this :
`	import os,shutil`     

`     	#clean up the /tmp folder	`
`	if os.path.isdir("/tmp") : `
 &nbsp;&nbsp;    `          os.system('rm -R /tmp/*')`
		
   

`     os.environ['JOBLIB_TEMP_FOLDER'] = '/tmp'	`  
`  	pandarallel.initialize(nb_workers = int(os.cpu_count())-1, use_memory_fs = False , progress_bar=True,verbose=2 ) 
`

**Comment by florianlaws** [comment]
What is the performance hit from not using the memory fs?

**Comment by till-m** [comment]
@chris-boson that seems reasonable. Would you be willing to make a pull request to that effect?

**Comment by ywsyws** [comment]
> > In my case I also had to clean up the /tmp folder.
> 
> Thanks ! combined the both solutions .
> 
> Like this : ` import os,shutil`
> 
> ` #clean up the /tmp folder ` ` if os.path.isdir("/tmp") : `    ` os.system('rm -R /tmp/*')`
> 
> ` os.environ['JOBLIB_TEMP_FOLDER'] = '/tmp' ` ` pandarallel.initialize(nb_workers = int(os.cpu_count())-1, use_memory_fs = False , progress_bar=True,verbose=2 ) `

In my case, this doesn't work. I'm working in a pod.

**Comment by shermansiu** [comment]
Now that #221 has been merged, I think this issue can be closed.
