### ISSUE TITLE
How to check if pandarallel already was initialized ?

### ISSUE THREAD

**Issue by borisRa** [nalepae/pandarallel#138]
Hi,

How can I check if pandarallel already was initialized  ?
Instead of running the row below every time before using pandarallel .
`pandarallel.initialize(nb_workers= int(os.cpu_count())-1, use_memory_fs = False ,progress_bar = False)`

Thanks,
Boris

**Comment by pratik-choudhari** [comment]
@borisRa There's no API to check if pandarallel was already initialized. If you are using jupyter, haven't restarted the kernel and have ran initialize() cell once, then we don't need to check for init. Also, initialize() doesn't reserve any resources so redoing it is safe.

**Comment by borisRa** [comment]
Thank you !
