### ISSUE TITLE
python3.9

### ISSUE THREAD

**Issue by jonathaw** [nalepae/pandarallel#145]
this looks really useful!
is there a plan to make this compatible with python3.9?

thanks!

**Comment by hadim** [comment]
Same here, I would be interested in support for py39.

**Comment by jorenham** [comment]
There is a PR for this https://github.com/nalepae/pandarallel/pull/142, but this repo appears to be abandoned

**Comment by nalepae** [comment]
Fixed in **pandarallel v1.5.3** and higher.
