### ISSUE TITLE
Global variable sharing

### ISSUE THREAD

**Issue by TsinlingLi** [nalepae/pandarallel#146]
import pandas as pd
import numpy as np

from pandarallel import pandarallel

pandarallel.initialize(nb_workers=4)

df = pd.DataFrame({'A': np.random.randint(1, 10, 2000), 'B': np.arange(2000)})
count = 0
def gb(df):
    global count
    count += 1
    return df.B.sum()

res = df.groupby('A').parallel_apply(gb)
print(count)

## The count value is 0

import pandas as pd
import numpy as np

from pandarallel import pandarallel

pandarallel.initialize(nb_workers=2)

df = pd.DataFrame(
    {
        'A': np.random.randint(1, 3, 5),
        'B': np.random.randint(1, 3, 5),
        'C': np.arange(5)
    }
)
df1 = pd.DataFrame(
    {
        'B': np.random.randint(1, 3, 5),
        'D': np.zeros(5)
    }
)
def gb(df):
    global df1
    df = pd.merge(df, df1, how='outer', on=['B'])
    if (df.D < 6).all():
        df['D'] = df.D + 1
    df1 = df[['B', 'D']].copy()
    df = df[['A', 'B', 'C', 'D']]
    return df

res = df.groupby('A').parallel_apply(gb)
print(res)
print(df1)

**Comment by guedriOussema** [comment]
Hello @TsinlingLi  , I am currently encountering the same issue, have you found a solution please?
