### ISSUE TITLE
ModuleNotFoundError: No module named 'pyarrow._plasma'

### ISSUE THREAD

**Issue by ElcoK** [nalepae/pandarallel#15]
When trying to import pandarallel, I get the following error:

`ModuleNotFoundError: No module named 'pyarrow._plasma'`

I am running this in a conda virtual environment, using python 3.7 and on a Windows 10 machine.

**Comment by VictorZuanazzi** [comment]
I am having the same problem. Any ideas of how to solve it?

**Comment by nalepae** [comment]
Well, it seems that PyArrow Plasma (the library which implement the shared memory used by Pandarallel) is not yet available on Windows (only Linux & macOS), as written [here](https://arrow.apache.org/docs/python/plasma.html) ...

So sorry, at the moment Pandarallel is not available on Windows.
As soon as PyArrow Plasma is available on Windows, Pandarallel should work.

**Comment by flrs** [comment]
On the dev side, we might want to watch the pull request https://github.com/apache/arrow/pull/3704 which will help with porting PyArrow Plasma to Windows.

**Comment by nalepae** [comment]
Merci beaucoup Florian,

As soon as it is merged, I will test it and release a new version of Pandarallel!

**Comment by nalepae** [comment]
Fixed on `pandarallel v1.6.0`.

Be sure to checkout the documentation.
