### ISSUE TITLE
Pandarallel apparently using one core in my machine

### ISSUE THREAD

**Issue by yashrsharma44** [nalepae/pandarallel#151]
## OS Specifications - 
```powershell
PS C:\Users\ASUS> wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu-18.04 (Default)
```

I am running my code using pandarallel and when I open `htop` to see the utilization of cores, I see - 
![image](https://user-images.githubusercontent.com/31438680/127764518-9b1acfea-2af9-4937-8e57-d9e9fbdcd48c.png)

This surprisingly using only 1 core of my CPU, which seems to be unnatural, as pandarallel is expected to utilize multiple cores.

Any idea about this?
I can share my code if you require, I have it in a private repo currently.

**Comment by nalepae** [comment]
Fixed on `pandarallel v1.6.0`.
WSL is not needed any more.

Be sure to checkout the documentation.
