### ISSUE TITLE
Incompatible with python 3.5

### ISSUE THREAD

**Issue by saqshamagrawal** [nalepae/pandarallel#16]
When I install this package into my python 3.5 project, I find that this piece of code: 
`msg = f"The pandarallel shared memory is too small to allow \ ...`
throws a
`SyntaxError: invalid syntax while importing`

I suppose the package uses f-strings for its error messaging, that first started in python 3.6. I am wondering if that is completely necessary, and if it can be removed to make the package compatible with 3.5. 

Thanks.

**Comment by nalepae** [comment]
Fixed in v1.1.0

**Comment by saqshamagrawal** [comment]
Thanks for the promptness. 

I ran into another issue (related to pickling of the function that I am trying to optimize), maybe I will open another issue if I can't get past it. But thanks anyway, it can be a big time saver for me once it works.

**Comment by nalepae** [comment]
Could you please show me the function (and the DataFrame structure) which does not work in your case ?
