### ISSUE TITLE
Not using all workers

### ISSUE THREAD

**Issue by arshdz** [nalepae/pandarallel#160]
I am using pandarallel on a 32 core machine but only two workers finish their task. Is there something that I am missing?
![image](https://user-images.githubusercontent.com/83593517/138067531-f67febda-3046-4f00-875c-d5c5aff26500.png)
![image](https://user-images.githubusercontent.com/83593517/138067821-ab15cf14-5eda-45ab-a885-1280c913f32d.png)

**Comment by vmarar** [comment]
You have nb_workers=4, remove that and it will use all available cpus by default

**Comment by arshdz** [comment]
No, it was using 2 of those 4 workers, when progress_bar=True is set. Works after removing it. Any reason why, and how to fix it?

**Comment by nalepae** [comment]
Yes, please use `pandarallel 1.5.7` and reopen if the issue is still here.
