### ISSUE TITLE
TypeError: _wrap_applied_output() got multiple values for argument 'not_indexed_same'

### ISSUE THREAD

**Issue by pwerth** [nalepae/pandarallel#168]
After upgrading Pandas from 1.3.5 to 1.4.0, I am now getting this error stemming from a basic 

`df.groupby(['col1', 'col2']).parallel_apply(my_func)`

Pandarallel v1.5.4

**Comment by nalepae** [comment]
Fixed in **Pandarallel v1.5.5**
