### ISSUE TITLE
Why doesn't it work on windows?

### ISSUE THREAD

**Issue by ma7555** [nalepae/pandarallel#169]
Hello @nalepae,

What are the restrictions not allowing this to run on Windows?
If you can point out to the part of the code that's not compatible I will try to fix and submit a PR.

Thanks!

**Comment by nalepae** [comment]
The main reason is the forking process supported by Windows.
Windows supports only `spawn`, when Pandarallel need `fork`.

Of course, if you achieve running Pandarallel with `spawn`, and more generally if you achieve running Pandarallel on windows, you're more thant welcome to do a PR!

**Comment by nalepae** [comment]
Fixed on `pandarallel v1.6.0`.

Be sure to checkout the documentation.
