### ISSUE TITLE
Does `pandarallel` parallelize across columns?

### ISSUE THREAD

**Issue by ktattan** [nalepae/pandarallel#171]
I see from the examples that you can use `rolling().parallel_apply()` which would be my use case. Although I'm not sure if `pandarallel` chunks by rows or columns.

Say I want to take a simple rolling average over a wide dataframe, say 2000 rows and 4000 columns - can / does `pandarallel` parallelize over the columns? By this I mean, say I have 4 cores, each core would get a chunk of 4000/4 = 1000 columns to apply the rolling mean to. Is my understanding correct here or is there something else happening under the hood?

Thanks for your help and for this library.

**Comment by till-m** [comment]
Hi @ktattan,

yes, that is indeed how the package works. The columns are distributed across cores and the results are then combined later on.
