### ISSUE TITLE
Fixing versioning for major refactors

### ISSUE THREAD

**Issue by fazalul92** [nalepae/pandarallel#173]
With the recent update to Pandarallel to v1.5.6, the major refactoring changes the way pandarallel gets initialized. i.e. it went from 
`from pandarallel.pandarallel import pandarallel` to `from pandarallel import pandarallel`. 

This breaks existing uses for pandarallel even when version number is loosely specified... `pandarallel~=1.5.4` would still try to pull v1.5.6. 

Although the fix is fairly simple, can the future releases with major changes also reflect on the version numbers as well?

**Comment by nalepae** [comment]
Hi,

Sorry I don't find any trace in the documentation (even if I go back to very old version of `pandarallel`) where the import process was:

```Python
from pandarallel.pandarallel import pandarallel
```
Could you tell me where did you see this pattern?

**Comment by fazalul92** [comment]
Sincere apologies for that. Now looking at the Github readme (and even other tutorials), I'm not sure how I ended up using that import process. Seems like it just used to work before `pandarallel.py` got deleted, and that code was moved to `core.py`.
