### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by heppytt** [nalepae/pandarallel#185]
I start parallel with a thread in the main function_ Apply didn't report an error, but I used a thread to call parallel in Django service first_ When applying the method, the following errors are reported. Can you help me have a look?
error:
OSError: [Errno 9] Bad file descriptor

**Comment by till-m** [comment]
Hi @heppytt,

I can have a look at this for you but I'll need more information. Could you please provide the following:

- **Operating System**
- **Python version**
- **Pandas version**
- **Pandarallel version**
- **Minimal but working code sample**

Thanks!

**Comment by till-m** [comment]
I'm assuming this is resolved. Feel free to re-open if the problem persists.
