### ISSUE TITLE
ArrowIOError: Could not connect to socket /tmp/test_plasma-pxm7ybav/plasma.sock

### ISSUE THREAD

**Issue by Gabrielvon** [nalepae/pandarallel#19]
Hi,

I installed pandarallel via `pip install pandarallel`. And it cannot initialized properly. It seems that I cannot connect to the socket and I cannot find the exact file mentioned in the error message though the folder exists. Please see below.

![image](https://user-images.githubusercontent.com/8952869/55770841-5d75e300-5ab8-11e9-864e-c3d4bb650661.png)

**Comment by nalepae** [comment]
Do you still have the same issue on last **Pandarallel** version?

**Comment by Gabrielvon** [comment]
Now is another error. It seems I updated my python version to 3.6.8 which some dependencies are not supporting yet.

<img width="566" alt="image" src="https://user-images.githubusercontent.com/8952869/62383056-8f3c1980-b581-11e9-9ef9-fecf38e7db11.png">

**Comment by nalepae** [comment]
Fixed with `pandarallel 1.4.0`
