### ISSUE TITLE
Rolling on datetime index

### ISSUE THREAD

**Issue by asmodaay** [nalepae/pandarallel#199]
Hi! Thanks for great job, it's really usefull!

When i'm trying to use parallel_apply on rolling df wtih time index, its drop TypeError
<img width="972" alt="image" src="https://user-images.githubusercontent.com/45363107/186206116-747073ac-454b-46ac-b941-156e903b40f0.png">

My df is :

<img width="285" alt="image" src="https://user-images.githubusercontent.com/45363107/186206202-c356e3c6-c84b-4733-a34b-ca583f846980.png">

If you will add supporting this rolling type it will be perfect!
Rolling with "time" window needs, when samples not equidistant.

**Comment by till-m** [comment]
Closed in favour of #180
