### ISSUE TITLE
Comparison?

### ISSUE THREAD

**Issue by hangtwenty** [nalepae/pandarallel#20]
Are there known differences/advantages/disadvantages of `pandarallel` vs for example ~Ray~ Modin? https://github.com/modin-project/modin

(Other things like Dask and Arrow are more clearly different scope, intentions, approaches... But `pandarallel` and `modin` do seem to have similar intents and approaches)

**Comment by nalepae** [comment]
`modin` does a lot of things `pandarallel` does NOT do, like reading CSV files.

`pandarallel` implements only 7 operations with multi process:
- `df.apply(func)`
- `df.groupby(args).apply(func)`
- `df.groupby(args1).col_name.rolling(args2).apply(func)`
- `series.map(func)`
- `series.apply(func)`
- `series.rolling(args).apply(func)`

Among them, `modin` does NOT implement:
- `df.groupby(args).apply(func)`
- `df.groupby(args1).col_name.rolling(args2).apply(func)`
- `series.rolling(args).apply(func)`

For these 3 operations, `modin` fallbacks on standard `pandas` operactions (no parallelization).

`pandarallel` implements also nice progress bars on `Jupyter Notebook` and console.

`pandarallel` does NOT rely on `pyarrow` (even if first versions of `pandarallel` did).
Consequently, `pandarallel` does NOT suffers of troubles citer [here](https://modin.readthedocs.io/en/latest/troubleshooting.html).

(For example with `pandarallel` you can always `Ctrl-C` an ongoing operation. If you do that with `modin` you'll get an `ArrowIOError: Broken Pipe` error, and you will have to restart your Python kernel.)

Please re-open this ticket if you need more informations!
