### ISSUE TITLE
parallel not working

### ISSUE THREAD

**Issue by riyaj8888** [nalepae/pandarallel#202]
I have pandas dataframe , inside it there is one text col and i want to apply custom text processing function on that column but parallel.map and .apply stuck in infinite loop.

what went wrong can u tell

**Comment by till-m** [comment]
Hi @riyaj8888,

can you please confirm that the issue is _not_ present when using `df.apply` instead of `df.parallel_apply`?

**Comment by till-m** [comment]
Closed due to inactivity -- feel free to reopen.
