### ISSUE TITLE
pandarallel freezes if progress bar is True and show multiprocessing related error if progress bar is False

### ISSUE THREAD

**Issue by hsnyn** [nalepae/pandarallel#204]
![image](https://user-images.githubusercontent.com/33712443/190544992-d66400a9-c5e7-494f-9cbd-905874b5df07.png)

**Comment by till-m** [comment]
Please fill in the information requested in the issue template, especially system information and provide a minimal, reproducible example (i.e. as described [here](https://stackoverflow.com/help/minimal-reproducible-example)).

**Comment by till-m** [comment]
Feel free to reopen with more information.
