### ISSUE TITLE
Dose the memory usage related to how many cores we use

### ISSUE THREAD

**Issue by wybert** [nalepae/pandarallel#205]
Hi, I am here to ask a question, not a bug report.
I see from the doc it said,

> pandarallel need twice the memory that standard pandas operation would normally use.

I am wondering if is there a way to reduce that by just using fewer cores. Dose the memory usage related to how many cores we use?

**Comment by nalepae** [comment]
> I am wondering if is there a way to reduce that by just using fewer cores. Dose the memory usage related to how many cores we use?

No, the memory usage is always twice the initial amount.
Pandarallel only sends the needed fraction of data to workers.

(Even if firsts versions of Pandarallel needed 1 full dataframe copy per worker, which was... quite a waste of memory usage!)

**Comment by starmpcc** [comment]
I think the memory consumption is proportional to nb_workers.
