### ISSUE TITLE
i can not install package

### ISSUE THREAD

**Issue by sungreong** [nalepae/pandarallel#21]
my version is ubuntu16.04 , python3.6.(anaconda)

but i cant install it

![image](https://user-images.githubusercontent.com/22166391/56726639-1b23f580-678a-11e9-947d-86752d102bab.png)

**Comment by damienlancry** [comment]
how did you solve this? i have the same problem

**Comment by nalepae** [comment]
It seems this error is raised with old versions of **pandarallel**.

Could you please try with the last one (**pandarallel v1.4.5**)
