### ISSUE TITLE
'functools.partial' object has no attribute '__code__' in Jupyter Notebooks

### ISSUE THREAD

**Issue by Meehai** [nalepae/pandarallel#210]
## General

- **Operating System**: Ubuntu 20.04
- **Python version**: 3.9.13
- **Pandas version**: 1.4.4
- **Pandarallel version**: 1.6.3

## Acknowledgement

- [x] My issue is **NOT** present when using `pandas` without alone (without `pandarallel`)
- [x] If I am on **Windows**, I read the [Troubleshooting page](https://nalepae.github.io/pandarallel/troubleshooting/)
      before writing a new bug report

## Bug description

`functool.partial` cannot be used in junction with jupyter notebooks and pandarallel

### Observed behavior

_Write here the observed behavior_

### Expected behavior

_Write here the expected behavior_

## Minimal but working code sample to ease bug fix for `pandarallel` team

```
import pandas as pd
from functools import partial
from typing import List
import numpy as np
from pandarallel import pandarallel

pandarallel.initialize(progress_bar=True)

def processing_fn(row: pd.Series, invalid_numbers: List[int], default: int) -> pd.Series:
    cond = row.isin(invalid_numbers)
    row[cond] = default
    return row

data = pd.DataFrame(np.random.randint(low=-10, high=10, size=(10000, 5)))
print("Before", (data.values == 100).sum())

fn = partial(processing_fn, invalid_numbers=[-5, 2, 5], default=100)
new_data = data.apply(fn, axis=1)

print("After serial", (new_data.values == 100).sum())

data = data.parallel_apply(fn, axis=1)
print("After parallel", (data.values == 100).sum())

```

Works fine in a standalone script, but fails if ran in Jupyter notebook

**Comment by till-m** [comment]
Hey, sorry for the delay. The scripts runs without issue for me, both inside jupyter notebooks and outside.

**Comment by Meehai** [comment]
Yeah, you are right, it seems to work now both on a local env and on some remote server. Perhaps it was a different issue that triggered this that I was not aware of.

I guess you can close it and I can submit a new one if I ever encounter it again.
