### ISSUE TITLE
Global variables cannot be used in parallel_apply with "name 'np' is not defined"

### ISSUE THREAD

**Issue by wubaosheng** [nalepae/pandarallel#214]
## General

- **Operating System**:windows
- **Python version**: 3.9.7
- **Pandas version**:1.1.5
- **Pandarallel version**:

## Acknowledgement

- [ 1] My issue is **NOT** present when using `pandas` without alone (without `pandarallel`)
- [1 ] If I am on **Windows**, I read the [Troubleshooting page](https://nalepae.github.io/pandarallel/troubleshooting/)
      before writing a new bug report

## Bug description
import numpy as np in the global, but when I use np in a new function for parallel_apply, name 'np' is not defined was occured. if re-import the numpy in the new function, it works.
### Observed behavior

_Write here the observed behavior_

### Expected behavior

_Write here the expected behavior_

## Minimal but working code sample to ease bug fix for `pandarallel` team

_Write here the minimal code sample to ease bug fix for `pandarallel` team_
```python
import pandas as pd
from pandarallel import pandarallel
import numpy as np
pandarallel.initialize(progress_bar=True)
df_size = int(1e6)
df = pd.DataFrame(dict(a=np.random.randint(1, 300, df_size),
                       b=np.random.rand(df_size)))
def function(x):
    return np.log2(x+1)
df.parallel_apply(function,axis=1)
```

![image](https://user-images.githubusercontent.com/50618480/208613703-d2aec5ec-3a24-4eb6-b9a2-eae39ad844ff.png)

**Comment by till-m** [comment]
Please read the page about [troubleshooting on windows](https://nalepae.github.io/pandarallel/troubleshooting/).
