### ISSUE TITLE
issue with more groupie levels

### ISSUE THREAD

**Issue by bicepjai** [nalepae/pandarallel#23]
Adding more group by level shows 
TypeError: Series.name must be a hashable type

```
    import math
    df_size = int(3e3)
    df = pd.DataFrame(dict(a=np.random.randint(1, 1000, df_size),
                        b=np.random.randint(1, 50, df_size),
                        c=np.random.rand(df_size)))
    def func(df):
        dum = 0
        for item in df.c:
            dum += math.log10(math.sqrt(math.exp(item**2)))
            
        return dum / len(df.b)
    res_parallel = df.groupby(["b"], as_index=False).parallel_apply(func)
```

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-58-ccc4e016e07e> in <module>
>      10 
>      11     return dum / len(df.b)
> ---> 12 res_parallel = df.groupby(["b"], as_index=False).parallel_apply(func)
> 
> ~/Programs/anaconda3/envs/nand-reports-p3/lib/python3.7/site-packages/pandarallel/_pandarallel.py in wrapper(*args, **kwargs)
>      72             """Please see the docstring of this method without `parallel`"""
>      73             try:
> ---> 74                 return func(*args, **kwargs)
>      75 
>      76             except _PlasmaStoreFull:
> 
> ~/Programs/anaconda3/envs/nand-reports-p3/lib/python3.7/site-packages/pandarallel/_pandarallel.py in closure(df_grouped, func, *args, **kwargs)
>     217                                    ])),
>     218                                    index=_pd.Series(list(df_grouped.grouper),
> --> 219                                    name=df_grouped.keys)
>     220                      ).squeeze()
>     221             return result
> 
> ~/Programs/anaconda3/envs/nand-reports-p3/lib/python3.7/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
>     266         generic.NDFrame.__init__(self, data, fastpath=True)
>     267 
> --> 268         self.name = name
>     269         self._set_axis(0, index, fastpath=True)
>     270 
> 
> ~/Programs/anaconda3/envs/nand-reports-p3/lib/python3.7/site-packages/pandas/core/generic.py in __setattr__(self, name, value)
>    5087             object.__setattr__(self, name, value)
>    5088         elif name in self._metadata:
> -> 5089             object.__setattr__(self, name, value)
>    5090         else:
>    5091             try:
> 
> ~/Programs/anaconda3/envs/nand-reports-p3/lib/python3.7/site-packages/pandas/core/series.py in name(self, value)
>     400     def name(self, value):
>     401         if value is not None and not is_hashable(value):
> --> 402             raise TypeError('Series.name must be a hashable type')
>     403         object.__setattr__(self, '_name', value)
>     404 
> 
> TypeError: Series.name must be a hashable type

**Comment by nalepae** [comment]
Fixed in v1.1.1.

Thanks for the bug report !
