### ISSUE TITLE
cant run on python3.6

### ISSUE THREAD

**Issue by BTFKM** [nalepae/pandarallel#246]
- os centos
- python3.6
- pandarallel version  lastest

python3.6 not support time.time_ns, and case import error
`ImportError: cannot import name 'time_ns'`

anyway to fix that? or any working version?

**Comment by BTFKM** [comment]
i googled and copied another way from other python3.6 time_ns issus :D

edited import code:
`try:
    from time import time_ns
except ImportError:
    from datetime import datetime
    # For compatibility with Python 3.6
    def time_ns():
        now = datetime.now()
        return int(now.timestamp() * 1e9)`

**Comment by till-m** [comment]
Python 3.6 actually reached EoL [a year ago](https://endoflife.date/python), so we decided against support it. Glad you found a workaround that works for you though!
