### ISSUE TITLE
Notice on maintenance

### ISSUE THREAD

**Issue by till-m** [nalepae/pandarallel#249]
Hey Everyone (especially @nalepae),

I hope you're doing well.

Due to a bunch of commitments piling up on my plate I've had to reorganize my priorities, leading to a decision to cease actively maintaining this project. This has been coming for a while, as I've caught my activity in this repo decreasing over the last few months.

I will try and help out here and there, as much as I can, but I don't want to make any promises.

Cheers,
Till

**Comment by nalepae** [comment]
Hi @till-m!

Thanks a lot for the incredibly valuable contributions you brought to Pandarallel during all this time!
I perfectly understand your priorities :)

It was a real pleasure to work with you, and you'r welcome at any time if you want to continue to contribute!

I wish you the best,

Manu

**Comment by till-m** [comment]
Thanks Manu, I appreciate it!
