### ISSUE TITLE
progress bar not working in jupyterlab

### ISSUE THREAD

**Issue by zouhx11** [nalepae/pandarallel#26]
I tried `pandarallel.initialize(progress_bar=True)`, but still can't see any expected progress bar

**Comment by nalepae** [comment]
Could you show me the output and the error message (if any) you get?

**Comment by zouhx11** [comment]
<img width="953" alt="屏幕快照 2019-06-04 上午12 15 10" src="https://user-images.githubusercontent.com/12454682/58817334-1b06f780-865e-11e9-84bc-8447deab7ee9.png">

**Comment by zouhx11** [comment]
As we can see, the progress bar doesn't work properly.

**Comment by nalepae** [comment]
As written in the documentation:

> **WARNING:** Progress bar is an experimental feature. This can lead to a considerable performance loss. Not available for DataFrameGroupy.parallel_apply.

The progress bar is not available for `DataFrameGroupy.parallel_apply`.

If you have time and want to implement it, I'll be happy to accept a pull request !
