### ISSUE TITLE
Memory usage increases across multiple `parallel_apply`

### ISSUE THREAD

**Issue by hogan-roblox** [nalepae/pandarallel#264]
## General

- **Operating System**: Linux
- **Python version**: 3.10.8
- **Pandas version**: 1.5.3
- **Pandarallel version**: 1.6.5

## Acknowledgement

- [x] My issue is **NOT** present when using `pandas` without alone (without `pandarallel`)
- [x] If I am on **Windows**, I read the [Troubleshooting page](https://nalepae.github.io/pandarallel/troubleshooting/)
      before writing a new bug report

## Bug description
If I run continuous data processing tasks, each with a huge DataFrame using `parallel_apply` , their MEM footprints somehow accumulates.

### Observed behavior

My code logic looks like below.
```
pandarallel.initialize(progress_bar=True, nb_workers=120)

for file_path in file_paths:
    df = pd.read_csv(file_path)
    df = pd.DataFrame.from_dict(
        df.sample(frac=1.0).parallel_apply(SOME_FUNCTION, axis=1).to_dict(),
        orient="columns",
    )
```

All tasks should have similar footprints in MEM. However, from the below image, one can tell the MEM drops after the first task is finished but soon climbs back up after loading the second task.
<img width="1758" alt="image" src="https://github.com/nalepae/pandarallel/assets/70972517/bb8b78a1-0ee7-42e8-b740-0a194fa182fb">

### Expected behavior

Given that two tasks have similar MEM footprints, I would assume the MEM pattern to be repeated but not accumulated.

## Minimal but working code sample to ease bug fix for `pandarallel` team

As the pseudocode I attached above.

**Comment by hogan-roblox** [comment]
I have some updates on this -- it seems that `pandarallel.initialize(progress_bar=True, nb_workers=120)` has to be re-executed between different data frames. Is it expected?

The below updated code somehow solves the issue for me.
```
for file_path in file_paths:
    pandarallel.initialize(progress_bar=True, nb_workers=120)
    df = pd.read_csv(file_path)
    df = pd.DataFrame.from_dict(
        df.sample(frac=1.0).parallel_apply(SOME_FUNCTION, axis=1).to_dict(),
        orient="columns",
    )
```

<img width="1753" alt="image" src="https://github.com/nalepae/pandarallel/assets/70972517/3819c445-6f15-4937-8b94-41d23fa730fb">

This issue is no longer a blocker for me, but I would like to leave open for a while to see if someone else has the same issue and whether this is an expected behavior.

**Comment by shermansiu** [comment]
Could you please attach a sample CSV and the simplest `SOME_FUNCTION` for which you can reproduce your error?

I'm unable to reproduce your problems with the memory usage.

> Python: 3.10.13
Pandarallel: 1.6.5
Pandas: 2.2.0

```python
import pandas as pd
import pandarallel

pandarallel.pandarallel.initialize(progress_bar=True, nb_workers=120)

for _ in range(10):
    df = pd.DataFrame({"foo": range(100_000)})
    df = pd.DataFrame.from_dict(
        df.sample(frac=1.0).parallel_apply(lambda x: x+1, axis=1).to_dict(),
        orient="columns",
    )
```

You mentioned that this issue is no longer a blocker for you, so if you don't reply in a while, this issue should probably be closed.

**Comment by hogan-roblox** [comment]
@shermansiu Thank you very much for taking the time to investigate this issue, and I apologize for my delayed response.

I have identified a potential cause of the memory leak in my SOME_FUNCTION. Previously, I was making REST API calls using requests.session() without properly utilizing the context manager pattern. After addressing this issue, the memory usage has significantly improved.

I will close this ticket now :)
