### ISSUE TITLE
Python 2.7 Compatibility

### ISSUE THREAD

**Issue by ijoseph** [nalepae/pandarallel#29]
As is indirectly mentioned [here](https://github.com/nalepae/pandarallel/issues/17), 2.7 compatibility would be useful. Although admittedly, this is only relevant for another 5½ months.  until it's officially deprecated.

**Comment by nalepae** [comment]
[This issue](https://github.com/nalepae/pandarallel/issues/17) explains the contrary: It is still possible to install **Pandarallel** with **Python 2.7** while it should not...

Actually, **Pandarallel** uses specific features such as [Concurrent futures](https://docs.python.org/3/library/concurrent.futures.html), introduced with **Python 3.2**.

If you find a smart way to use only **Python 2** features, if you have time, and if you want to do it, I'll be happy to accept a pull request!

But as you said, **Python 2** will be officially deprecated end of this year, and **pip** already announced they may stop **Python 2** support shortly after this date ...
