### ISSUE TITLE
issues of df.groupby(args).parallel_apply(func)

### ISSUE THREAD

**Issue by araura2000** [nalepae/pandarallel#30]
Looks like this error is raised when the program combines the indices of dataframes.

InvalidIndexError: Reindexing only valid with uniquely valued Index objects.

  File "/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2740, in get_indexer
    raise InvalidIndexError('Reindexing only valid with uniquely'

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

**Comment by nalepae** [comment]
Could you please give me the portion of code (with the dataframe) leading to this issue?

If you don't want to give me the dataset as is because of confidentiality reasons, please replace values by placeholders.

Thanks!

**Comment by nalepae** [comment]
I close because of no answer for more than 2 months.
Please re-open this ticket if you want to update it.
