### ISSUE TITLE
is there any deinitialize?

### ISSUE THREAD

**Issue by beckhz** [nalepae/pandarallel#33]
when run the code pandarallel.initialize(), my system build up a process:
eversec   79659      1  0 11:02 pts/1    00:00:00 /home/everdc/anaconda3/lib/python3.6/site-packages/pyarrow/plasma_store_server -s /tmp/test_plasma-2680t0g9/plasma.sock -m 2000000000

the more the code run, the more the process build.
so, is there any deinitialize func to kill the process?

**Comment by nalepae** [comment]
In 1.2.0, I did **not** implement a way to deinitialize, but I now ensure that at most 1 `plasma_store_server` process is running at a time.

(So if you call several times `pandarallel.initialize`, **Pandarallel** will first destroy the previous `plasma_store_server` process then will create a new one).
