### ISSUE TITLE
Can not kill the program on pycharm

### ISSUE THREAD

**Issue by Jun-Zhang-32108** [nalepae/pandarallel#35]
Hi,

I use one single line to call df.parallel_apply() as the following:
"label['content_segmented'] = label.parallel_apply(content_segementation.segmentation_content, axis=1)"

It is supposed to show 4 progress bars because I have a 4-core cpu in my laptop but it only showed one. It is fine because I can see that the program was running one 4 cores ( 8 threads). But when I tried to kill the program I found I could not. Even though I close the tap on PyCharm it was still running in all cores. Why is that? How can I kill the program running in halfway?

![image](https://user-images.githubusercontent.com/45533650/61512598-007db780-aa2d-11e9-83dd-8d26918b3780.png)

![image](https://user-images.githubusercontent.com/45533650/61510741-c6a9b280-aa26-11e9-86cd-96a7ee22e3db.png)

**Comment by nalepae** [comment]
Fixed in `pandarallel v1.4.0`.

This issue comes from the usage of `pyarrow plasma`.
`pandarallel v1.4.0` does not use `pyarrow plasma` anymore.
