### ISSUE TITLE
progress_bar=True does not work with Pandas 0.25.0

### ISSUE THREAD

**Issue by wiseyoungbuck** [nalepae/pandarallel#36]
Pandas broke tqdm integration with version 0.25.0. And thusly, it seems to have broken pandarellel as well.
see: tqdm/tqdm#780

The default behavior seems to work fine, but the progress bars are broken.

**Comment by nalepae** [comment]
Thanks for the report !

**Comment by nalepae** [comment]
Fixed in v1.3.1.
