### ISSUE TITLE
ImportError: cannot import name 'time_ns' after install on ubuntu and python 3.6.8

### ISSUE THREAD

**Issue by roger-paris** [nalepae/pandarallel#38]
Hi,

I currently try to use this package into our demo. As you see, the version of python min >= 3.5. I am using python 3.6.8. After installing this package, when running some "parallel_apply", we could see the following error:

from time import time_ns
ImportError: cannot import name 'time_ns'

Thanks for your support!
Roger

**Comment by ptynecki** [comment]
I can confirm the issue. I have Python 3.6.8 x64 on Ubuntu 18.04.

The ImportError exceptions came with the newest pandarallel v1.3.1 package update.

**Comment by Dajre** [comment]
Also occurs in python 3.6.5, pretty sure this was introduced in the last 24 hours, was working fine yesterday.
