### ISSUE TITLE
Indefinite run

### ISSUE THREAD

**Issue by iamtodor** [nalepae/pandarallel#39]
Hello,

I have found your library on Medium and wanted to try it out.
I did base preparation such as 
```python
from pandarallel import pandarallel
# Initialization
pandarallel.initialize(progress_bar=True)
```
and I use it for a single column dataframe:
```python
def make_request(uid):
    uid = int(uid)
    url = some_endpoint
    response = requests.post(url).json()
    return response['total']
    
start = datetime.now()
print(start)
data[1].iloc[:50].parallel_apply(make_request, axis=1)
print('time elapsed', datetime.now() - start)
```

I see the following string under the Jupyter Lab cell: `VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=5750), Label(value='0 / 5750'))), …` but the cell is running indefinitely.
The regular pandas's apply works for about 25 secs

What did I wrong?

**Comment by mikelkl** [comment]
Same here, happens in Jupyter Notebook.
Any Idea?

**Comment by nalepae** [comment]
Looks like you have 2 different issues:
One display issue and an other hidden behind.

Could you please retry with `pandarallel v1.4.0` with Jupyter Notebook, or with Jupyter Lab but **after** having applied the last question of the *troubleshooting* section in the *README* ? 

(Or simply run
```
$ pip install ipywidgets 
$ jupyter nbextension enable --py widgetsnbextension
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
)

**Comment by nalepae** [comment]
Closing because of no answer for almost two months.

Please reopen if you have any news about it!
