### ISSUE TITLE
Clear Pool/Add Option to Clear Pool

### ISSUE THREAD

**Issue by lukeolson13** [nalepae/pandarallel#41]
With current `pool` use (have only tested with `series.parallel_apply`, but I'd assume this happens anywhere you have a `pool.<x>map` call), the child processes are kept in memory after results have been returned. I believe this is intended behavior from Pathos, as it allows for the reuse of pools if called again; however, this can cause memory issues if a script continues to execute after any pandarallel functions are called (ie the script requires additional memory usage later on that is now occupied by the zombie child processes).

You can get around this by calling `pool.clear()` once you have your results, and child processes will be cleared and release the memory hold. I'm not sure how much of an impact this has on performance for any later pool usage (I didn't notice any difference in testing, but I'd assume there is at least some), so this could be added as optional input if hard-coding doesn't seem like the route to go here.

Open to other thoughts/ideas on how to better handle these as well.

**Comment by nalepae** [comment]
Fixed with `pandarallel 1.4.0`

`pandarallel 1.4.0` does not use `pathos` any more.
