### ISSUE TITLE
Logging of python error

### ISSUE THREAD

**Issue by maxmahlke** [nalepae/pandarallel#43]
First of, great package! The fact that I just had to add two lines of code to get a speedup of factor 4 is amazing.
I was wondering where I have to look for potential errors thrown by my python code. E.g. I had failed to declare a variable in a subroutine and the progress bar just froze at the step instead of raising the syntax error. Is there a logfile where errors are written to?

**Comment by nalepae** [comment]
Thanks for your message!

`pandarallel 1.4.0` partially solve your issue:

If an error is raised, the corresponding progress bar will be in red, and at the end the corresponding error will be raised in the stack trace (as with the classic `pandas` behavior).

See following gif, at 16% for the first progress bar.

![error](https://user-images.githubusercontent.com/4943830/68535979-4bf50200-034b-11ea-8624-296c8a55e623.gif)

Unfortunatly, you'll have en wait for the end of all tasks before being able to see the error.

I close your ticket, and open a new one with this specific issue.
