### ISSUE TITLE
ModuleNotFoundError: No module named 'ipywidgets'

### ISSUE THREAD

**Issue by xieshuaix** [nalepae/pandarallel#44]
Seemed to be installation dependency problem.
Replicated on two machines with fresh conda environment. pandarallel is installed via pip.
Solved by manually install ipywidgets.

During import pandarallel:
    from .pandarallel import pandarallel
    from .dataframe import DataFrame
    from .utils import (parallel, chunk, ProgressBarsConsole, ProgressBarsNotebookLab)
    from ipywidgets import HBox, VBox, IntProgress, Label
ModuleNotFoundError: No module named 'ipywidgets'

**Comment by gfdonnay** [comment]
I also encountered this

**Comment by nalepae** [comment]
Fixed in `pandarallel v1.3.4`.

Please do `$ pip install -U pandarallel`

**Comment by ThomasTel** [comment]
This is still an issue in 1.6.5 (with Python 3.12).
