### ISSUE TITLE
`parallel_apply` does not work on second run

### ISSUE THREAD

**Issue by scottlittle** [nalepae/pandarallel#46]
When I try to run `parallel_apply' twice, it does not work the second time and just hangs.  Perhaps add a reinitialize option or terminate option to clear the current instance.

**Comment by nalepae** [comment]
It seems your bug comes from the usage of `pyarrow plasma`. `pandarallel 1.4.0` does not use `pyarrow plasma` any more.

Could you please try with `pandarallel 1.4.0` and reopen this ticket if the problem still appears ?
