### ISSUE TITLE
Permission denied: '/usr/local/lib/python3.6/dist-packages/pyarrow-0.15.0-py3.6-linux-x86_64.egg/pyarrow/plasma-store-server'

### ISSUE THREAD

**Issue by redfever84** [nalepae/pandarallel#51]
As a root (ubuntu 18.04, python3.6), trying to run some code:

```
from pandarallel import pandarallel

pandarallel.initialize()
```
I am getting "Permission denied" in the very beginning:
```
New pandarallel memory created - Size: 2000 MB
Pandarallel will run on 56 workers
Traceback (most recent call last):
  File "pokusy_only_linux.py", line 3, in <module>
    pandarallel.initialize()
  File "/usr/local/lib/python3.6/dist-packages/pandarallel-1.3.3-py3.6.egg/pandarallel/pandarallel.py", line 75, in initialize
    verbose=verbose_store)
  File "/usr/local/lib/python3.6/dist-packages/pandarallel-1.3.3-py3.6.egg/pandarallel/plasma_store.py", line 29, in start_plasma_store
    proc = subprocess.Popen(command, stdout=stdout, stderr=stderr)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/pyarrow-0.15.0-py3.6-linux-x86_64.egg/pyarrow/plasma-store-server'
```

**Comment by nalepae** [comment]
Did you installed `pandarallel` with the account (root here) than the account where you run your python script ?

I'm currently developing a new version of **Pandarallel** without **PyArrow Plasma** (which seems to be the cause of your bug).

This version is not yet relased, but you can already try it by:
- Cloning this git repository on your computer
- Switching to **develop** branch
- Running `$ pip install .` (with the dot after the install)

By default, this version of **Pandarallel** will try to use `/dev/shm` to transfer data between the main process and the workers. If you don't want to use this feature but you prefer to use standard multiprocessing tranfert feature (pipe), you can disable it by passing `use_memory_fs_is_available=False` in the initialize method.

See the docstring of `initialize` for more information.

**Comment by redfever84** [comment]
Thank you for your advice, issue was that pyarrow was not installed as a root.

**Comment by nalepae** [comment]
`pandarallel 1.4.0` does not use `pyarrow` any more. Your problem should be solved with this version.
