### ISSUE TITLE
Progressbar fails with non-standard index

### ISSUE THREAD

**Issue by lepmik** [nalepae/pandarallel#61]
Hi, first of all thank you for making this nice package. I ran into some issues when using non standard index values:
![image](https://user-images.githubusercontent.com/3418096/71318929-b1cec080-2497-11ea-8aa8-6a3d09f29c54.png)

**Comment by nalepae** [comment]
Thanks for your bug report, I can reproduce it myself too.

As a workaround, you can disable the progress bar. It works without the progress bar on my computer.

**Comment by nalepae** [comment]
Fixed in `pandarallel v1.4.4`. Please reopen if you still have the same issue.
