### ISSUE TITLE
parallel_map hangs if progress_bar=True

### ISSUE THREAD

**Issue by sirbiscuit** [nalepae/pandarallel#75]
Hello!

When pandarallel is configured with `progress_bar = True` and `parallel_map` is executed more than once, it stops working. The following code demonstrates this problem:

```python
import pandas as pd
from pandarallel import pandarallel
pandarallel.initialize(progress_bar=True)
pd.Series(range(1000000)).parallel_map(lambda n: n+1)
pd.Series(range(1000000)).parallel_map(lambda n: n+1)
```

The first call of parallel_map works fine, but the second call hangs forever:

![image](https://user-images.githubusercontent.com/8418161/73455251-f50e3000-436f-11ea-9af2-a892164810af.png)

If `progress_bar` is set to `False`, this problem does not occur. I use pandarallel version 1.4.5 on Linux. This issue might be related to #68.

**Comment by ddonetskov** [comment]
I experience the same issue. Using pandarallel 1.4.5 with Python 3.7.5 on Ubuntu 18.04, typically with 28 workers (as per the number of cores). Most of time, some workers become very slow with processing and, eventually, will stuck. Sometimes, they succeed. I have not managed to figure out any pattern to differentiate the cases. 

The type of processing I use is a quite complex procedure which use external libraries. The resources do not seem to be an issue, I monitor that with top/htop/sar and I can see there is still plenty of free memory and the cpu queue is not large. 

Disabling the progress bar (which is not convinient) do the trick as in workers do not stuck any longer.

I am going to try Python 3.7.6 (positively mentioned in #68 ) but it is not a good option for my Linux distro as it is not in the standard repositories yet.

**Comment by sirbiscuit** [comment]
Indeed, upgrading to Python 3.7.6 does the trick.

**Comment by daxid** [comment]
I'm using Python 3.8.6 and it still happens...
I did not try downgrading to Python 3.7.6, and don't really want to...

**Comment by xxllp** [comment]
why??
