### ISSUE TITLE
Parallelization does not work if multiple arguments are passed to function

### ISSUE THREAD

**Issue by ogencoglu** [nalepae/pandarallel#83]
For example the following will run _one process at a time_:

```
pandarallel.initialize(progress_bar=True)
data['comment'] = data['comment'].parallel_apply(clean_string, args=(lang_model,))
```

due to the `args` part, as `clean_string` function requires multiple arguments.

**Comment by nalepae** [comment]
I cannot reproduce your issue.
Bellow the piece of code I used trying to reproduce it.

Thus, I notice difference between `func(1, 1)` and `square`. `square` takes less time to run than `func(1, 1)`. But this difference is noticeable with "classical" pandas too, not only with pandarallel.

```
import pandas as pd
from pandarallel import pandarallel
pandarallel.initialize(progress_bar=True)

df = pd.DataFrame(dict(a=[i for i in range(10**7)]))

def func(item, power_1, power_2):
    return item ** (power_1 + power_2)

def square(item):
    return item**2

df.a.apply(func, args=(1, 1))
df.a.apply(square)

df.a.parallel_apply(func, args=(1, 1))
df.a.parallel_apply(square)
```

Could you please provide a minimal piece of code (dataframe and function to apply) for me to reproduce your issue?

**Comment by ogencoglu** [comment]
I couldn't have time to get back to this so I will close this for now.
