### ISSUE TITLE
parallel_apply sometimes changes the element type (example provided)

### ISSUE THREAD

**Issue by petrbel** [nalepae/pandarallel#84]
We found out that (sometimes) `parallel_apply` changes the dtypes of the underlying series. I've able to reproduce this with strings.

**Minimal not-working example:**
- construct basic dataframe with few strings
- force dtype to be `str`
- assert that the series elements are strings (run both `apply` and `parallel_apply`)
- everything is ok
- force dtype to be `string` ([official pandas documentation suggests this way](https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html#behavior-differences))
- assert that the series elements are strings (run both `apply` and `parallel_apply`)
- while `apply` is ok, `parallel_apply` is (in some cased) fed with `numpy.array` instead of expected strings.

```python
import pandas as pd
from pandarallel import pandarallel


def assert_str(s):
    assert isinstance(s, str), 'Unexpected type: ' + str(type(s))


if __name__ == "__main__":
    pandarallel.initialize(nb_workers=5)  # Note: some other nb_workers are ok

    # Create small df full of strings
    df = pd.DataFrame({'headline': ['News 1', 'News 2', 'News is here', 'News 3', 'News 4', 'News 5', 'News 6', 'News 7']})

    # Set dtype to `str`
    df['headline'] = df['headline'].astype(str)

    print('(str) Apply')
    df['headline'].apply(assert_str)  # ok
    print('\tok')

    print('(str) Parallel apply')
    df['headline'].parallel_apply(assert_str)  # ok
    print('\tok')

    # Set dtype to 'string'
    df['headline'] = df['headline'].astype('string')  # ok

    print('(string) Apply')
    df['headline'].apply(assert_str)  # ok
    print('\tok')

    print('(string) Parallel apply')
    df['headline'].parallel_apply(assert_str)  # ERROR, numpy instead of string
    print('\tok')
```

Thanks @floopcz and @gdynusa for help finding this out!
Tagging also @hurin @nechcigithub

Glad to implement a PR if somebody poke me in the right direction.

**Comment by till-m** [comment]
Hi @petrbel.

I apologize for the delay. Thanks for reporting this problem and the minimal example. I tried running it and it seems fine, no error is produced. As a result, I will close this issue, though feel free to reopen if the problem persists.
