### ISSUE TITLE
Bug with the progressbar

### ISSUE THREAD

**Issue by mbahin** [nalepae/pandarallel#97]
Hi!

Thanks for the nice tool! :)

I have an error only if I use the progress bar

`TypeError: ("argument of type 'int' is not iterable", 'occurred at index M05218:191:000000000-D7R5H:1:1102:14482:19336')`

It works well without the bar...
Any idea?

Cheers,
Mathieu

**Comment by nalepae** [comment]
Should be fixed on `pandarallel v1.6.0`.

Please reopen this ticket if it is not the case.
